# Generated by Django 4.1 on 2022-09-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('title', models.TextField()),
                ('rating', models.DecimalField(decimal_places=5, max_digits=10)),
                ('release_data', models.DateField()),
                ('review', models.TextField()),
            ],
        ),
    ]
