# Generated by Django 4.1 on 2022-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_mywatchlist_filmwatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwatchlist',
            name='release_data',
            field=models.TextField(),
        ),
    ]
