# Generated by Django 4.1 on 2022-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_filmwatchlist_release_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwatchlist',
            name='rating',
            field=models.FloatField(),
        ),
    ]
