# Generated by Django 4.1 on 2022-09-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_filmwatchlist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwatchlist',
            old_name='release_data',
            new_name='release_date',
        ),
    ]
