# Generated by Django 4.1 on 2022-09-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_rename_release_data_filmwatchlist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwatchlist',
            name='release_date',
            field=models.DateField(),
        ),
    ]
