# Generated by Django 4.1 on 2022-09-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0006_alter_filmwatchlist_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmWatchList',
            new_name='MyWatchList',
        ),
    ]
